### ISSUE TITLE
reproduce old dangling close parenthesis behaviour

### ISSUE THREAD

**Issue by fommil** [daniel-trinh/scalariform#29]
although I agree entirely with the new trailing newline behaviour, there does not appear to be a way to reproduce the old behaviour. This makes it difficult to include this version of scalariform in projects until it is safe to do a global reformat.

Please consider including a flag that reproduces the old behaviour.

**Comment by RichardBradley** [comment]
(Please could we rename this issue to something more like "reproduce old "dangling close parenthesis" behaviour", to match the name of the setting? I initially thought this issue would be about newlines at the end of files.)

I've had the same problem, and I'd go even further -- I think the new default is wrong.

See e.g. [Scala Style Guide chapter "Indentation"](http://docs.scala-lang.org/style/indentation.html) which has:

```
foo(
  someVeryLongFieldName,
  andAnotherVeryLongFieldName,
  "this is a string",
  3.1415)
```

and not:

```
foo(
  someVeryLongFieldName,
  andAnotherVeryLongFieldName,
  "this is a string",
  3.1415
)
```

However, "Programming in Scala" by Odersky et al (2nd ed) does appear to use the "dangling" style. See e.g. p106:

```
  new Rational(
    numer * that.denom + that.numer * denom,
    demon * that.denom
  )
```

and e.g. p445:

```
button.addActionListener(
  function2ActionListener(
    (_: ActionEvent) => println("pressed!")
  )
)
```

So it looks to me like this needs to be an option, as styles differ.

This used to be  (partially?) controlled by the `PreserveDanglingCloseParenthesis` option, which was added in commit 0cf353 , when “format(ArgumentExprs)” looked like:

```
--- a/scalariform/src/main/scala/scalariform/formatter/ExprFormatter.scala
+++ b/scalariform/src/main/scala/scalariform/formatter/ExprFormatter.scala
@@ -133,7 +133,11 @@ trait ExprFormatter { self: HasFormattingPreferences with AnnotationFormatter wi

   def format(argumentExprs: ArgumentExprs)(implicit formatterState: FormatterState): FormatResult = argumentExprs match {
     case BlockArgumentExprs(contents)                 ⇒ format(contents)
-    case ParenArgumentExprs(lparen, contents, rparen) ⇒ format(GeneralTokens(List(lparen)) :: contents)
+    case ParenArgumentExprs(lparen, contents, rparen) ⇒
+      var formatResult = format(GeneralTokens(List(lparen)) :: contents)
+      if (formattingPreferences(PreserveDanglingCloseParenthesis) && hiddenPredecessors(rparen).containsNewline && contents.nonEmpty)
+        formatResult = formatResult.before(rparen, formatterState.currentIndentLevelInstruction)
+      formatResult
   }
```

In the current version, the option is present but completely ignored, and this method now always adds a newline before the closing paren.

Was that deliberate? I can’t find any discussion of it in the commit history which has touched these files. 

The b65bfc65a commit removed the "PreserveDanglingCloseParenthesis" option from the README, but the commit comment didn't discuss it at all: "update scala 2.10 version"

I think we need to:
 * Reinstate the `PreserveDanglingCloseParenthesis` option, or something similar
 * Perhaps fix the option to be a little more agressive, changing code to match the configured style, rather than just "preserve"?

**Comment by fommil** [comment]
:+1:

**Comment by andrebeat** [comment]
Just wanted to say that I was in the process of migrating a project to use this "fork" and noticed this too, as it reformatted every single file of the project. I agree that this is a major code style decision that should be up to the user of the library to make (like it was before).

**Comment by fommil** [comment]
@andrebeat actually it wasn't up to the user before. It simply didn't work. The problem is that there is no way to get the old behaviour back (a sensible choice only for regressions like this).

**Comment by RichardBradley** [comment]
> > this is a major code style decision that should be up to the user of the library to make (like it was before).
>
> @andrebeat actually it wasn't up to the user before. It simply didn't work. 

I imagine he is referring to old versions from before commit 0cf3536, when `scalariform` would leave closing parentheses alone and neither convert them to dangling style (as it does now) nor ask the user what to do (as we are proposing).

In any case, I think the fix is clear. Someone just needs to do the dev work :-)

It's unlikely to be me any time soon, but I might get around to it in a few months if no-one else does it.

**Comment by fommil** [comment]
@daniel-trinh @mdr FYI https://groups.google.com/d/msg/scala-ide-dev/zeC2uFBOlV8/i80VaIf9AQAJ
