### ISSUE TITLE
Where is the active home of scalariform?

### ISSUE THREAD

**Issue by RichardBradley** [daniel-trinh/scalariform#55]
re the discussion at https://github.com/mdr/scalariform/issues/130

Please could you clarify the following?
 * Is this now "the current "considered active" fork" of scalariform?
  * Considered by whom?
  * How might scalariform users know to use this fork instead of mdrs?
 * Do you publish a JAR to any public Maven repos?
  * The latest I can find is https://maven-repository.com/artifact/org.scalariform/scalariform_2.10/0.1.4 which was publised by `mdr` on 2013-04-24
 * What is fixed here v.s. the `mdr` original?
 * Do you accept PRs for new features, or just fixes?
 * Do you know what `mdr` thinks about the project?

Thanks,

Rich

**Comment by daniel-trinh** [comment]
* __Is this now "the current "considered active" fork" of scalariform?__
  - As far as I know, this is the most active branch.
* __Considered by whom?__
  - I can't speak for others. What I will tell you is that I've received requests to maintain this branch from maintainers of Scala IDE, Ensime, and OSS contributers at Twitter.
* __How might scalariform users know to use this fork instead of mdrs?__
  - The ideal would be to leave a note in the readme in mdr's fork, or get contributor access to his branch. Short of that, leaving comments in issues redirecting people to this branch would be helpful.
* __Do you publish a JAR to any public Maven repos?__
  - Yes, see http://search.maven.org/#search%7Cga%7C1%7Cscalariform
* __What is fixed here v.s. the mdr original?__
  - See https://github.com/daniel-trinh/scalariform/blob/master/CHANGELOG . The new releases since mdr's last release  are `0.1.5` and `0.1.6`.
* __Do you accept PRs for new features, or just fixes?__
  - Fixes are usually simple enough to accept PRs for. For features, it depends on the feature. Opening up a ticket to start a discussion is the best way to get things started.
* __Do you know what mdr thinks about the project?__
  - I don't know of his exact thoughts, but he has given me the right to publish to `org.scalariform` in maven central and sonatype. Take what you will from that.

**Comment by RichardBradley** [comment]
Thanks, that's very helpful.

> The ideal would be to leave a note in the readme in mdr's fork,

That would be ideal. I'll comment on mdr#130

>  For features, it depends on the feature. Opening up a ticket to start a discussion is the best way to get things started.

Thanks, will do.

**Comment by RichardBradley** [comment]
> > What is fixed here v.s. the mdr original?
>
> See https://github.com/daniel-trinh/scalariform/blob/master/CHANGELOG . The new releases since mdr's last release are 0.1.5 and 0.1.6.

Looks like one of my possible PRs is already fixed here -- I have independently added a fix for "`SpacesAroundMultiImports`" before discovering this fork (sigh).
