### ISSUE TITLE
Scaladoc lists

### ISSUE THREAD

**Issue by charpov** [daniel-trinh/scalariform#78]
I'm using lists in Scaladoc:
```
      /** Documentation
        *
        *  - item 1
        *  - item 2
        */
```
Note the __two__ spaces between `*` and `- item 1`, which are necessary to make it a list.  My problem is that scalariform reduces these two spaces to one, thus destroying the list structure.

Is there a way to deal with that?

**Comment by charpov** [comment]
No news on this?  It continues to mess up my code between sbt and IntelliJ IDEA.  Is there a way to turn off scalariform entirely for scaladoc comments?

**Comment by daniel-trinh** [comment]
It looks like its possible to modify the code to not strip out extra leading whitespace. 

There's a few things that can be done:

+ Special case when the first character is the start of a scaladoc list to not strip leading whitespace
+ Add a new preference to allow no formatting of comments
+ Change the behavior in general to not strip out leading whitespace
+ Adding another preference to enable or disable trimming of whitespace in comments

The first option seems to be the "smartest", although there seem to be other reasons why someone might want to disable commenting on comments, so that might be useful to implement regardless. Not stripping out whitespace might be OK too, will need to think about this some more what the best solution is.

**Comment by sschaef** [comment]
This issue was moved to scala-ide/scalariform#168
